- hosts: localhost
  vars:
    vcenter_validate_certs: False
    gather_facts: False
    vcsa_ip: '192.168.123.90'
    datastore_name: local
  tasks:
  - name: add the host in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*vcenter.test.*'
      line: "192.168.123.90 vcenter.test vcenter"
      state: present
    become: true

  - name: add gateway.test (192.168.123.1) in too /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '^192.168.123.1 gateway.test gateway\s.*'
      line: "192.168.123.1 gateway.test gateway"
      state: present
    become: yes

  - name: Reload the dnsmasq instances
    command: sudo pkill -HUP dnsmasq
    become: true
  - name: Ensure we can resolve the vcsa host
    command: host vcenter 192.168.123.1
  - name: Ensure we can resolve the vcsa FQDN
    command: host vcenter.test 192.168.123.1
  - name: Validate the reverse DNS resolution of the vcsa IP
    shell: "nslookup vcenter.test 192.168.123.1|grep vcenter"
  - import_role:
      name: vcenter-instance
    vars:
      vcenter_instance:
        installation:
          from: 'iso'
          iso_path: "{{ '~/Downloads/' + lookup('env','VERSION') + '.iso' | expanduser }}"
        network:  # IP Configuration of the vcenter
          address: '{{ vcsa_ip }}'
          prefix: 24
          gateway: 192.168.123.1
          dns: 192.168.123.1
          hostname: vcenter.test
        esxi:
          hostname: '{{ hostvars["esxi-vcenter"].ansible_host }}'
          username: root
          password: '!234AaAa56'

  - name: clean up the host in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: "192.168.123.90 vcenter.test vcenter"
      state: absent
    become: true

  - name: add gateway.test (192.168.123.1) in too /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: "192.168.123.1 gateway.test gateway"
      state: absent
    become: yes
  - name: Reload the dnsmasq instances
    command: sudo pkill -HUP dnsmasq
    become: true

