- hosts: vcenter
  gather_facts: false
  tasks:
    - raw: |
             shell
             chsh -s /bin/bash root
    - meta: reset_connection
      become: true

- hosts: vcenter
  tasks:
    - command: service-control --stop
      ignore_errors: yes
    - systemd:
        state: stopped
        name: '{{ item }}'
      with_items:
        - multi-user.target
        - applmgmt
        - getty@tty1.service
        - getty@tty2.service
        - vami-lighttp
        - dnsmasq
        - vmafdd
        - vmcad
        - vmdird
        - vmdnsd
        - vmtoolsd
        - vmware-firewall
        - vmware-pod
        - xinetd
        - vmware-vpxd
        - vmware-stsd
        - vmware-sts-idmd
        - vmware-vmon
        - syslog
        - syslog.socket
      ignore_errors: yes
    - command: "pkill -f '/usr/bin/python /usr/lib/applmgmt/ddns/py/ddns.py'"
      ignore_errors: yes

    - shell: |
        set -eux
        for mount_point in $(mount|awk '/mapper/ { print $3 }'); do
            echo $mount_point
            if ! test -d ${mount_point}.new; then
                cp -Rvpa ${mount_point} ${mount_point}.new
            fi
            umount ${mount_point}
            rm -r ${mount_point}
            mv -f ${mount_point}.new ${mount_point}
        done
    - copy:
        dest: /etc/fstab
        content: |
            /dev/vda3 / ext4 defaults 1 1
            /dev/vda2       swap    swap    defaults        0       0
            /dev/vda1 /boot ext4 defaults,nosuid,noacl,nodev,noexec 1 2
            /dev/cdrom /mnt/cdrom iso9660 ro,noauto,nosuid,nodev 0 0
    - copy:
        dest: /etc/systemd/network/10-eth0.network
        content: |
            [Match]
            Name=eth0
            [Network]
            DHCP=yes
            [DHCP]
            UseDNS=no
            UseMTU=yes
            UseHostname=no
    - copy:
        dest: /etc/dnsmasq.conf
        content: |
            listen-address=127.0.0.1
            bind-interfaces
            user=dnsmasq
            group=dnsmasq
            no-negcache
            #no-hosts
            log-queries
            log-facility=/var/log/vmware/dnsmasq.log
            domain-needed
            dns-forward-max=150
            cache-size=8192
            neg-ttl=3600
            server=1.1.1.1
            server=8.8.8.8
    - name: Remove any potential link pointing to /run/systemd/resolve/resolv.conf
      file:
        dest: /etc/resolv.conf
        state: absent
    - copy:
        dest: /etc/resolv.conf
        content: |
            nameserver 127.0.0.1
    - copy:
        dest: /usr/local/bin/mtu_fix
        content: |
            #!/bin/bash
            for i in $(seq 20); do
                sleep 5
                if [ "$(ip r show default)" = "" ]; then
                    dhcp_mtu=$(journalctl -k -o cat|awk "/eth0 changing MTU from 1500 to/ {print \$8}"|tail -n1)
                    ip l set mtu ${dhcp_mtu} eth0
                    exit
                fi
            done
        mode: '0755'
    - copy:
        dest: /lib/systemd/system/mtu_fix.service
        content: |
            [Unit]
            Description=Work around for https://github.com/systemd/systemd/issues/9102 and https://github.com/systemd/systemd/issues/9408
            After=local-fs.target network-online.target network.target
            Wants=local-fs.target network-online.target network.target
            [Service]
            ExecStart=/usr/local/bin/mtu_fix
            Type=oneshot
            [Install]
            WantedBy=multi-user.target
    - systemd:
        enabled: true
        name: mtu_fix
    - copy:
        dest: /etc/systemd/resolved.conf
        content: |
            [Resolve]
            LLMNR=false

    - name: Inject the SSH key in /root/.ssh/authorized_keys
      copy:
        dest: /etc/cloud/cloud.cfg
        content: |

            users:
               - name: root
                 lock-passwd: false
            disable_root: false
            disable_vmware_customization: true
            preserve_hostname: true
            datasource_list: [
                              NoCloud,
                              ConfigDrive,
                              OpenStack,
                              None
                             ]
            cloud_init_modules:
             - bootcmd
             - write-files
             - growpart
             - resizefs
             - users-groups
             - ssh
            cloud_config_modules:
             - package-update-upgrade-install
             - runcmd
             - yum-add-repo
            cloud_final_modules:
             - scripts-vendor
             - scripts-per-once
             - scripts-per-boot
             - scripts-per-instance
             - scripts-user
             - ssh-authkey-fingerprints
             - final-message
            system_info:
               distro: photon
               paths:
                  cloud_dir: /var/lib/cloud/
                  templates_dir: /etc/cloud/templates/
               default_user:
                 name: root
                 lock_passwd: False
               ssh_svcname: sshd
    - lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin Yes'

    - lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^Banner'
        line: '# Banner /etc/issue'

    - name: Purge cloud-init files
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /var/lib/cloud
        - /var/log/cloud-init.log
        - /var/log/cloud-init-output.log
    - command: "systemctl enable {{ item }}"
      with_items:
        - cloud-init
        - cloud-config
        - cloud-init-local
    - name: Disable root's password
      user:
        name: root
        password: '!'
