- hosts: vcenter
  gather_facts: false
  tasks:
    - raw: |
             shell
             chsh -s /bin/bash root

- hosts: vcenter
  tasks:
    - systemd:
        state: stopped
        name: '{{ item }}'
      with_items:
        - multi-user.target
        - applmgmt
        - getty@tty1.service
        - getty@tty2.service
        - vami-lighttp
        - dnsmasq
        - vmafdd
        - vmcad
        - vmdird
        - vmdnsd
        - vmtoolsd
        - vmware-firewall
        - vmware-pod
        - xinetd
        - vmware-vpxd
        - vmware-stsd
        - vmware-sts-idmd
        - vmware-vmon
        - syslog
        - syslog.socket
    - command: "pkill -f '/usr/bin/python /usr/lib/applmgmt/ddns/py/ddns.py'"
      ignore_errors: yes

    - shell: |
        set -eux
        for mount_point in $(mount|awk '/mapper/ { print $3 }'); do
            echo $mount_point
            if ! test -d ${mount_point}.new; then
                cp -Rvpa ${mount_point} ${mount_point}.new
            fi
            umount ${mount_point}
            rm -r ${mount_point}
            mv -f ${mount_point}.new ${mount_point}
        done
    - copy:
        dest: /etc/fstab
        content: |
            /dev/vda3 / ext4 defaults 1 1
            /dev/vda2       swap    swap    defaults        0       0
            /dev/vda1 /boot ext4 defaults,nosuid,noacl,nodev,noexec 1 2
            /dev/cdrom /mnt/cdrom iso9660 ro,noauto,nosuid,nodev 0 0
    - copy:
        dest: /etc/systemd/network/10-eth0.network
        content: |
            [Match]
            Name=eth0
            [Network]
            DHCP=yes
            [DHCP]
            UseDNS=yes
            UseMTU=yes
    - copy:
        dest: /lib/systemd/system/mtu_fix.service
        content: |
            [Unit]
            Description=Work around for https://github.com/systemd/systemd/issues/9102
            After=local-fs.target network-online.target network.target
            Wants=local-fs.target network-online.target network.target
            [Service]
            ExecStart=/bin/bash -c "/bin/sleep 5; /usr/bin/systemctl restart systemd-networkd"
            Type=oneshot
            [Install]
            WantedBy=multi-user.target
    - systemd:
        enabled: true
        name: mtu_fix
    - copy:
        dest: /etc/systemd/resolved.conf
        content: |
            [Resolve]
            LLMNR=false

    - name: Inject the SSH key in /root/.ssh/authorized_keys
      copy:
        dest: /etc/cloud/cloud.cfg
        content: |

            users:
               - name: root
                 lock-passwd: false
            disable_root: false
            disable_vmware_customization: true
            preserve_hostname: false
            datasource_list: [
                              NoCloud,
                              ConfigDrive,
                              OpenStack,
                              None
                             ]
            cloud_init_modules:
             - bootcmd
             - write-files
             - growpart
             - resizefs
             - set_hostname
             - update_hostname
             - users-groups
             - ssh
            cloud_config_modules:
             - package-update-upgrade-install
             - runcmd
             - yum-add-repo
            cloud_final_modules:
             - scripts-vendor
             - scripts-per-once
             - scripts-per-boot
             - scripts-per-instance
             - scripts-user
             - ssh-authkey-fingerprints
             - final-message
            system_info:
               distro: photon
               paths:
                  cloud_dir: /var/lib/cloud/
                  templates_dir: /etc/cloud/templates/
               default_user:
                 name: root
                 lock_passwd: False
               ssh_svcname: sshd
    - lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin No'
